### ISSUE TITLE
Add option for custom endpoint

### ISSUE THREAD

**Issue by zupat** [daaru00/obsidian-aws-s3-sync#1]
Could you possibly add an option for custom endpoints so we could use other s3 compatible provider (eg: backblaze,wasabi). The [S3Client Constructor](https://github.com/daaru00/obsidian-aws-s3-sync/blob/fc6647230509015ff0fa68f149e216d49b55049f/src/lib/filemanager.ts#L200) has an endpoint field so this should be straightforward.

**Comment by daaru00** [comment]
Hi @jinyus,

can you take a look at the [latest release](https://github.com/daaru00/obsidian-aws-s3-sync/releases/tag/0.9.0)'s changes? Let me know if it works as expected 😉

**Comment by zupat** [comment]
Thanks for implementing this, but I no longer use this app because I wanted something that works on mobile, but I looked at the code and it should work now.
