### ISSUE TITLE
Cloud not find any AWS profiles

### ISSUE THREAD

**Issue by ghost** [daaru00/obsidian-aws-s3-sync#2]
Hello daaru.

Thank you for this plugin.

I'm having trouble configuring the plugin with my aws account.

I have a local file like this : C:\Users\\[username]\\.aws\credentials (created using the CLI command aws configure): 

```
[default]
aws_access_key_id = xxxxxxx 
aws_secret_access_key = xxxxxxxxxxxx
```

When I'm trying to test the configuration, I keep getting an error.

![image](https://user-images.githubusercontent.com/10338113/158778444-ef085485-3ed9-4d0b-8448-bd79f89db843.png)

The default profile seems to work as the CLI is responding using it : 

![image](https://user-images.githubusercontent.com/10338113/158778688-7c41d823-e0ec-4c0c-a033-2aa035bdd861.png)

Can you help me ?

**Comment by daaru00** [comment]
Hi @adrienbuffet,

oops, sorry, my fault :grin: there was an issue parsing credentials file, I hadn't tested it well. 

Could you try with the [0.9.1](https://github.com/daaru00/obsidian-aws-s3-sync/releases/tag/0.9.1) version if it resolves the issue?

**Comment by ghost** [comment]
It's working ;)
![image](https://user-images.githubusercontent.com/10338113/158811133-e9e02702-0eb4-402e-ace4-f1ff1808d7a0.png)

**Comment by ghost** [comment]
Thanks for the fast reply and the hotfix.
